There is some fail. maybe some double free when the Python interpreter is terminated, 
however, the result is generated and due to switch to mcell 4 we will ignore this issue for now.


Thread #1 [python] 8886 [core: 10] (Suspended : Signal : SIGABRT:Aborted)	
	__GI_raise() at raise.c:51 0x7ffff784ffff	
	__GI_abort() at abort.c:89 0x7ffff785142a	
	__libc_message() at libc_fatal.c:175 0x7ffff788dc00	
	malloc_printerr() at malloc.c:5,049 0x7ffff7893fc6	
	_int_free() at malloc.c:3,905 0x7ffff789480e	
	_wrap_delete_output_column_list() at pymcellPYTHON_wrap.c:6,720 0x7fffe630ce53	
	_PyMethodDef_RawFastCallDict() at call.c:518 0x5555556909c9	
	_PyCFunction_FastCallDict() at call.c:582 0x555555690ae1	
	object_vacall() at call.c:1,198 0x555555682f3e	
	PyObject_CallFunctionObjArgs() at call.c:1,263 0x555555683089	
	SwigPyObject_dealloc() at pymcellPYTHON_wrap.c:1,695 0x7fffe6319a58	
	dict_dealloc() at dictobject.c:1,905 0x555555663968	
	subtype_dealloc() at typeobject.c:1,241 0x555555701971	
	frame_dealloc() at frameobject.c:470 0x5555556cc930	
	function_code_fastcall() at call.c:291 0x5555556cc930	
	_PyFunction_FastCallKeywords() at call.c:408 0x5555556cc930	
	call_function() at ceval.c:4,616 0x555555724846	
	_PyEval_EvalFrameDefault() at ceval.c:3,124 0x555555724846	
	_PyEval_EvalCodeWithName() at ceval.c:3,930 0x55555566a4f9	
	PyEval_EvalCodeEx() at ceval.c:3,959 0x55555566b3c4	
	PyEval_EvalCode() at ceval.c:524 0x55555566b3ec	
	run_mod() at pythonrun.c:1,035 0x555555783874	
	PyRun_FileExFlags() at pythonrun.c:988 0x55555578db81	
	PyRun_SimpleFileExFlags() at pythonrun.c:429 0x55555578dd73	
	pymain_run_file() at main.c:427 0x55555578ee5f	
	pymain_run_filename() at main.c:1,627 0x55555578ee5f	
	pymain_run_python() at main.c:2,877 0x55555578ee5f	
	pymain_main() at main.c:3,038 0x55555578ee5f	
	_Py_UnixMain() at main.c:3,073 0x55555578ef7c	
	__libc_start_main() at libc-start.c:291 0x7ffff783d2e1	
	_start() at start.S:103 0x555555734122	
