The error in this model is due to wrong argument. 
However the error message us super long abd user might not know what't going on.

Pybind11 uses list.__repr__ and it was not clear how to fix this.   

Cube = m.GeometryObject(
    name = 'Cube',
    vertex_list = Cube_vertex_list,
    element_connections = ...
    
